### PR TITLE
I'd like to get images with special `propertyType` and nothing more.

### PR DESCRIPTION
**Pull request by makskolesnikov**
E.g.: only open graph images and nothing more.
```
import LinkPreview from 'react-native-link-preview';

LinkPreview.getPreview('http://fb.com', 'og');
```

### CODE REVIEW

**Comment by ospfranco** [comment]
May I ask the reasoning behind this change? maybe a use case?

**Comment by makskolesnikov** [comment]
@ospfranco Hello!
I'm trying to display in my chat some previews card by URL.
I want to be able to display the image only if it contains the property ('og').

<details>
  <summary>Click to show example</summary>
simulator screen shot 15 nov 2017 16 41 39

</details>

**Comment by ospfranco** [comment]
hey, sorry I haven't had a lot of time to review this change, please give me until the weekend

**Comment by ospfranco** [comment]
Hey sorry for the delay, I really had no time, checking the code this seems to be the important change right?

```nodes = doc(`meta[property='${propertyType || 'og'}:image']`);```

but I'm not understanding how this will help you fetch only the 'og' images?

**Comment by ospfranco** [comment]
ah, my bad, did not see:

```if (images.length <= 0 && !propertyType) {```

ok, I'm not sure about the consistency of the api, maybe it would be better to pass an options object in the second param though, as this may grow over time

**Comment by ospfranco** [comment]
Merged, will change the API though

**Comment by ospfranco** [comment]
published under v.1.3.0

**Pull request merged**
