### PR TITLE
Remove dependency on 'es6-promise' which breaks React Native Android

### PR DESCRIPTION
**Pull request by haider-plero**

### CODE REVIEW

**Comment by ospfranco** [comment]
Do you have a reproducible example? on which device/react-native version does this break?

**Comment by ospfranco** [comment]
unfortunately the polyfill is not removable without breaking compatibility with ES5, which is a problem for certain environments outside of react-native, feel free to open an issue with more information (at least a reproducible example) so I can check what exactly breaks.

**Comment by haider-plero** [comment]
It breaks the React Native <> Native bridge on Android. My React Native version is `0.56` and the promise returned by `AsyncStorage.getItem` is not resolving which is the first use of bridge in my app.

**Comment by ospfranco** [comment]
I installed the latest version in a new project this morning and everything worked fine, there might be some conflict with some other library you are using. 

In any case I'm not removing the polyfill, as stated, for compatibility reasons.

**Pull request closed without merging**
